version: "3.9"
services:
  webserver: 
    image: webserver
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 81:80
      - 443:443
    volumes:
      # - nginx_logs:/etc/nginx/logs
      - ./logs/webserver:/var/log/nginx
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: backend:latest
    hostname: backend
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 8000:8000
    environment:
      - SERVICE_LOGS_DIR=/teacheetah/logs
    command:
      - gunicorn
      - --bind
      - 0.0.0.0:8000
      - app:init_app
      - --reload
      - --worker-class
      - aiohttp.GunicornWebWorker
      - --access-logfile 
      - '-'
    volumes:
      # - backend_logs:/teacheetah/logs
      - ./logs/backend:/teacheetah/logs
      - ./:/teacheetah/
volumes:
  nginx_logs:
  backend_logs:
